name: Mizuame Pages
on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: false

jobs:
    build:
        runs-on: macos-latest
        timeout-minutes: 10
        steps:
            - run: echo "Hello, world!"
            - name: Install Hugo
              run: |
                brew --version
                brew install hugo
                hugo version
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup themes
              run: git clone https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke
            - name: Build with Hugo
              run: hugo -d public/
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./public/
            - name: Test
              run: |
                ls -la
    deploy:
        permissions:
          contents: read
          pages: write
          id-token: write
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.url}}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
