name: Mizuame Pages
on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: false

jobs:
    build:
        runs-on: macos-latest
        timeout-minutes: 10
        steps:
            - run: echo "Hello, world!"
            - name: Install Hugo
              run: |
                brew --version
                brew install hugo
                hugo version
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build with Hugo
              run: hugo -d public/
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./public/
            - name: Test
              run: ls -la
